import-context:

  diksiResource:
    name: name
    httpHtmlParsedObjects:
      -
        uri: https://dixy.ru/catalog/
        headers:
            -
              key: PAGEN_1
              value: 1-50
              type: ITERABLE

        httpMethod: GET




  name: str
  fileParseProperties:
    -
      path: src/main/resources/cities.json
      className: com.example.food_basket_optimization.pojo.CityFromFile
      isList: true
  httpJsonParseObjects:
    -
      className: com.example.food_basket_optimization.pojo.StoreFromMegaMarket
      uri: https://sbermarket.ru/api/stores/1
      httpMethod: GET
      body: null
      isList: false

  htmlParsedObjects:








